### ISSUE TITLE
Cloud support missing

### ISSUE THREAD

**Issue by JanneKiiskila** [ARMmbed/easy-connect#12]
The current COAP server addresses only cover old "Connector", i.e. connect.mbed.com.
```
#ifndef MESH
// This is address to mbed Device Connector
#define MBED_SERVER_ADDRESS "coap://api.connector.mbed.com:5684"
#else
// This is address to mbed Device Connector
#define MBED_SERVER_ADDRESS "coaps://[2607:f0d0:2601:52::20]:5684"
```

These addresses do not match the Cloud servers, so we should instead offer either a configurability item to choose to which one to connect or simply remove it completely here.

**Comment by janjongboom** [comment]
@JanneKiiskila How about adding `MBED_CLOUD_SERVER_ADDRESS` defines?

**Comment by yogpan01** [comment]
Not needed, those are not handled through APIs. Its handled through their own config files so should not be an issue.
