### ISSUE TITLE
Document connection error codes?

### ISSUE THREAD

**Issue by n-eq** [ARMmbed/easy-connect#21]
Are there any plans to write some documentation (or to simply add a a section in README file) to explain the different codes when the connection fails?
I had a very hard time finding out what the 3010 code meant due a connection failure...

**Comment by janjongboom** [comment]
The errors are documented here: https://docs.mbed.com/docs/mbed-os-api-reference/en/latest/APIs/communication/network_sockets/#network-errors

But it would be good to link to that page from the README of easy-connect, let me make a PR for that.

**Comment by janjongboom** [comment]
See #23
