### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by mapellil** [ARMmbed/easy-connect#53]
Error: Class "mbed::ATCmdParser" has no member "process_oob" in "easy-connect/esp8266-driver/ESP8266/ESP8266.cpp", Line: 278, Col: 23

**Comment by janjongboom** [comment]
@mapellil Can you run `mbed deploy` in the easy-connect folder?

**Comment by DuyTrandeLion** [comment]
I also have the same error and I used the online compiler

**Comment by janjongboom** [comment]
@DuyTrandeLion Which project are you using?

**Comment by DuyTrandeLion** [comment]
I am using it with the Hello MQTT example on mbed and I update all libraries to the latest version

**Comment by JanneKiiskila** [comment]
I just compiled the Hello MQTT example with the on-line compiler using K64F, it worked just fine. Quite a few warnings, though - but it still compiled a working binary for K64F. So, there arew now some other details that you need to share:
- what target
- what network stack
at least come to mind.

**Comment by DuyTrandeLion** [comment]
I use the esp8266 v1 module with the Nucleo L432KC. The old version worked fine but when I used update all the error appeared. I think this is the conflict between libraries. May be I can use the old version for my project

**Comment by mapellil** [comment]
Nothing related to target or stack, simply the ATCmdParser in mbedos doesn't define the process_oob() called in the ESP8266.cpp

**Comment by DuyTrandeLion** [comment]
So is there any way to fix it? Thanks

**Comment by mapellil** [comment]
I can add i'm referring to https://github.com/ARMmbed/mbed-os/#ca661f9d28526ca8f874b05432493a489c9671ea  

 if you works from online compiler, and not using 8266 drv, just comment out the process_oob() in ESP8266.cpp. A more clean workaround should be to create in the prj top folder a file .mbedignore to exclude from compilation the 8266 (create it from the GitGUI as from Windows it seems to me impossible)

**Comment by DuyTrandeLion** [comment]
mapellil thanks

**Comment by JanneKiiskila** [comment]
Most of the drivers have now been updated so that we don't need an `.mbedignore` -file, is this issue still valid?

**Comment by JanneKiiskila** [comment]
Closing out as non-active case. If issue persists, please open a new issue with necessary details.
