### ISSUE TITLE
.lib files

### ISSUE THREAD

**Issue by mapellil** [ARMmbed/easy-connect#54]
When the library is imported in online compiler the contained .lib files are seen by the build system as modified even if left untouched (probably they contains some "strange" characters).

**Comment by JanneKiiskila** [comment]
Can you please specify exactly which .lib-files you mention here? Compiling which application?

**Comment by JanneKiiskila** [comment]
Closing out as non-responsive. I think the `.gitignore` file updates should fix this issue, if I **guess** correctly. Please raise a new issue with more defails if you find this insufficient.
