### ISSUE TITLE
Cannot find ATCmdParser.h

### ISSUE THREAD

**Issue by DuyTrandeLion** [ARMmbed/easy-connect#55]
I use easy-connect with MQTT example on mbed online compiler and I received this when I tried using my ESP8266 module 
"Error: Cannot open source input file "ATCmdParser.h": No such file or directory in "easy-connect/esp8266-driver/ESP8266/ESP8266.h", Line: 20, Col: 26"

Anyone knows how to fix this? Thank you

**Comment by janjongboom** [comment]
@JanneKiiskila ping.

**Comment by teetak01** [comment]
Online compiler issues belong to Mbed OS team. @screamerbg can you direct to right person?

**Comment by teetak01** [comment]
Issues #54 and #53 are probably also related on online compilers.

**Comment by betzw** [comment]
Have you tried to update your mbed-os lib in your online-compiler project?

**Comment by DuyTrandeLion** [comment]
Thanks everyone. I use the older version of this lib and it worked fine for me

**Comment by JanneKiiskila** [comment]
Tried out just recently against K64F and latest easy-connect (v1.2.11) - compiles just fine. Closing out as non-reproducing.

- Well, it reproduces if I let the mbed-os.lib pointer be a really old one (like 5.3 something). Update the mbed-os to a more recent on, 5.9 compiles well.
