### ISSUE TITLE
I have to pass WiFi credential (SSID/Passw) through NFC tag so w/o recompiling the .json file, how to do this with easy-connect?

### ISSUE THREAD

**Issue by mapellil** [ARMmbed/easy-connect#56]

**Comment by janjongboom** [comment]
@mapellil I'd suggest to not use easy-connect, but directly reference the WiFi driver in your application. Then you can also load the WiFi credentials from NVM or flash.

**Comment by mapellil** [comment]
I'd suggest to modify the easy-connect to allow run time passing of the SSID/Passw, this make sense to me. I've never seen a device that needs to recompile/flash the code to change the wifi connection.

**Comment by janjongboom** [comment]
@mapellil It's because easy-connect is a library which makes it easy to distribute demo's / reference apps regardless of connectivity method of the user's board. If you're not using it for that, just use the normal WiFi library for your board. Then you can inject the SSID / Password using any way you want, no compilation necessary.

F.e. for ODIN:

```cpp
#include "OdinWiFiInterface.h"

int main() {
     OdinWiFiInterface wifi;
     wifi.connect("Your SSID", "Your password", NSAPI_SECURITY_WPA_WPA2);

     NetworkInterface *network = &wifi;

     // rest of your app
}
```

**Comment by teetak01** [comment]
@janjongboom @JanneKiiskila  maybe we should have a disclaimer that while we use easy_connect() in our reference examples, it is not designed for production applications and final products should skip easy_connect() and use Mbed OS directly. This library also is not optimised for RAM/ROM. Its mainly providing some reference for customers how they can quickly enable connectivity and get first ideas on how networking works in Mbed OS,

**Comment by mapellil** [comment]
Sorry if I insist: I'm not talking about products or optimizations, I'm referring exactly to demo/reference apps that often needs to moves on different Wifi (eg. at the customer premises or at exhibition). I think to support both the cases shouldn't be too complex (wifi credential passing through .json or at run time).

**Comment by JanneKiiskila** [comment]
@mapellil  - I sort of agree, we should be able to support both ways.

**Comment by JanneKiiskila** [comment]
https://github.com/ARMmbed/easy-connect/pull/59 should resolve this issue as well.

**Comment by JanneKiiskila** [comment]
#59 merged in now.
