### ISSUE TITLE
No internet handle

### ISSUE THREAD

**Issue by DuyTrandeLion** [ARMmbed/easy-connect#57]
Is there any functions that I can call to enable auto reconnect after the internet is lost? I haven't seen any function reconnecting.

Thank you

**Comment by JanneKiiskila** [comment]
That's not really resolved in this layer, you should just call connect() again.

**Comment by JanneKiiskila** [comment]
@teetak01  @TeroJaasko  - we should give this one a bit of thought...

**Comment by teetak01** [comment]
Closing as this repository has been deprecated with introduction of new network APIs in Mbed OS 5.10.
