### ISSUE TITLE
Don't define serial in easyconnect

### ISSUE THREAD

**Issue by JanneKiiskila** [ARMmbed/easy-connect#7]
we shouldn't define the serial in easyconnect, instead we should take it in as a parameter via the init() call.

Compile [  3.7%]: main.cpp
[Warning] arch.h@88,15: C++11 requires a space between string literal and macro [-Wc++11-compat]
[Error] main.cpp@28,18: conflicting declaration 'mbed::RawSerial output'
[Warning] main.cpp@162,57: 'osStatus rtos::Thread::start(T*, M) [with T = LedResource; M = void (LedResource::*)()]' is deprecated: The start function does not support cv-qualifiers. Replaced by thread.start(callback(obj, method)). [since mbed-os-5.1] [-Wdeprecated-declarations]
[ERROR] In file included from ./mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/debug.h:40:0,
                 from ./mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/opt.h:52,
                 from ./mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/netif.h:40,
                 from ./mbed-os/features/FEATURE_LWIP/lwip-interface/EthernetInterface.h:22,
                 from ./easy-connect/easy-connect.h:27,
                 from ./main.cpp:26:
./mbed-os/features/FEATURE_LWIP/lwip-interface/lwip/src/include/lwip/arch.h:88:15: warning: C++11 requires a space between string literal and macro [-Wc++11-compat]
 #define X8_F  "02"PRIx8
               ^
./main.cpp:28:18: error: conflicting declaration 'mbed::RawSerial output'
 RawSerial output(USBTX, USBRX);
                  ^~~~~
In file included from ./main.cpp:26:0:
./easy-connect/easy-connect.h:6:8: note: previous declaration as 'mbed::Serial output'
 Serial output(USBTX, USBRX);

As we get this...

**Comment by JanneKiiskila** [comment]
We shouldn't user serial at all, just plain printf() actually.

**Comment by JanneKiiskila** [comment]
This one was also fixed.

**Comment by janjongboom** [comment]
Landed in #11.
