### ISSUE TITLE
New Network Interface for easy-connect

### ISSUE THREAD

**Issue by ghost** [ARMmbed/easy-connect#71]
I have developed a new Network Interface for the WNC M14A2A that I would like to contribute to the easy-connect repository. Wondering who the contact is I could discuss this with.

**Comment by ghost** [comment]
Interesting, no response in 4 days.  Is anyone watching this repository?

**Comment by teetak01** [comment]
@jflynn129 sorry, we are quite busy in multiple fronts.

**Comment by janjongboom** [comment]
@jflynn129 I'd suggest to just open a pull request against easy-connect. Or at least link to the repo where you implemented the driver. Also, responses over the weekend might be a bit delayed ;-)
