### ISSUE TITLE
configure cellular debugging

### ISSUE THREAD

**Issue by vidavidorra** [ARMmbed/easy-connect#84]
I think it would be very useful to add a modem debug flag to allow configuration (in `mbed_app.json`) of cellular debug trace, especially during error hunting or development phase.

I propose a documented entry in `mbed_app.json`
```json
    "modem_debug_on": {
      "help": "Value: Turns modem debug traces on. Options are true | false.",
      "macro_name": "MODEM_DEBUG_ON",
      "value": true
    },
```

And a section in the `easy_connect` function. I personally think this should be inside the first `if (log_messages) {` so that messages have to be enabled in the `easy_connect` call **and** `MODEM_DEBUG_ON` is true.
```c++
#if (MODEM_DEBUG_ON)
        cellular.modem_debug_on(true);
#endif
```

Let me know what you think and I'll create a pull-request for it.

**Comment by JanneKiiskila** [comment]
@mhiljane and @AnttiKauppila - how does this sound to you? Seems OK for me at least.

**Comment by teetak01** [comment]
Closing as this repository has been deprecated with introduction of new network APIs in Mbed OS 5.10.

**Comment by JanneKiiskila** [comment]
@SeppoTakalo  - potentially something to consider with Mbed OS networking side?
