### ISSUE TITLE
compiling uneeded files

### ISSUE THREAD

**Issue by netanelgonen** [ARMmbed/easy-connect#87]
while trying to compile Odin W2 Module that does not use any of the drivers inside this repository I have encountered compilation error from the drivers (that are not needed).
the driver files should not compile if not requested.

workaround: delete the drivers folders

**Comment by netanelgonen** [comment]
Hi @JanneKiiskila  can you please take a look at this issue.

**Comment by teetak01** [comment]
@netanelgonen there was a bug in one of the drivers that caused compilation to fail. It has been merged in now #88 

What you are otherwise asking, would require that every single driver would wrap their code in some Mbed OS and driver-specific compilation flag. We did this for the Mesh-drivers as those had some complicated dependencies. You can suggest such changes to the owners of the other drivers.

**Comment by JanneKiiskila** [comment]
Please put in the logs for the compilation errors here and raise issue to the respective non-compiling driver. @netanelgonen  Also, you do not need to delete the drivers - you can use `.mbedignore` -files.

**Comment by netanelgonen** [comment]
Hi @teetak01 , 
you can put the drivers under the folder 'TARGET_*' 
this way the driver will compile only if the target is relevant.
see example in https://github.com/ARMmbed/mbed-client-pal/tree/master/Configs/pal_config/mbedOS

@JanneKiiskila  deleting the files was a fast workaround just like adding the .medignore file
in the current situation that we are trying to save the binary size of the application, we should not compile extra files that contain global variables and definitions. specially not cpp constructors

**Comment by teetak01** [comment]
@netanelgonen you misunderstood, most of those drivers are owned by partners. We cannot make any codechanges, and so far there is no urgent need for that.

@netanelgonen open issue to the respective driver repository if you think there is some problems. Otherwise there should be no impact. Note that easy-connect really is EASY connect. Its for simple usage of multiple drivers.

**Comment by netanelgonen** [comment]
@teetak01  actually I understood perfectly.
I understand that the driver repository cannot be changed, but their location should change.
the location of each driver should be under a folder named 'TARGET_*' in this way the driver will compile only for this target. if you need a femily of targets you can always use the parent of the target.

have you looked in the exmaple from mbed-client-pal?
this will not chane the 'easy' of the code it will just save space and reduce the option for errors.

**Comment by JanneKiiskila** [comment]
Well, for any of the external Wi-Fi boards for example - you can connect them to pretty much any board, what would be the right TARGET_ then?

**Comment by netanelgonen** [comment]
is esp8266-driver is relevent for all board?
and wifi-ism43362?
or wifi-x-nucleo-idw01m1?

those are for specifec board targets (as far as i understeand)

**Comment by JanneKiiskila** [comment]
Those use serial for connection, so you can connect them to pretty much anything.
For WiFi-X, there's even 2 form factors - Arduino and Morpheus to suit different boards (driver is anyway the same, config just changes a tad).

**Comment by netanelgonen** [comment]
Hi @JanneKiiskila so what you are actually writing here that all driver is needed to all mbed-os targets?

**Comment by teetak01** [comment]
We do not actually know exactly which targets need which driver.

**Comment by netanelgonen** [comment]
so maybe enable the drivers only when knowing that there are needed for the target?

**Comment by JanneKiiskila** [comment]
Yes, the WiFi modules are all **universal**, they should work with pretty much any board you can throw them at.

**Comment by netanelgonen** [comment]
So @JanneKiiskila you think this is better to compile unneeded drivers and their constructors and so on just for the possibility that you will want one of those drivers is the way to go?

**Comment by JanneKiiskila** [comment]
Currently there is no mechanism for that, however. One should be invented. The drivers need to be usable even w/o easy-connect itself.

**Comment by teetak01** [comment]
Well, actual production application probably will not pull in easy-connect, and will instead use Mbed OS API directly. This is really easy-of-use wrapper library. If you do not care about the other drivers, just remove easy-connect completely. With Odin board especially, it does not need this for anything.

**Comment by JanneKiiskila** [comment]
Yes, indeed - if the example is targeting only ONE board with ONE connectivity, there is really no need to use easy-connect.

**Comment by netanelgonen** [comment]
so every one that use the appliaction need to delete this repo unless he useses a specific target?

**Comment by teetak01** [comment]
No, this is part of mbed-cloud-client-example and mbed-os-example-client. Both compile out-of-box without any changes. What issue you had was some more specific.

**Comment by netanelgonen** [comment]
actually, I'm the not specific user.
I'm trying to add new modules.....

**Comment by JanneKiiskila** [comment]
Well, if stuff now works out of the box as is - and then doesn't, then it sounds more like the new driver might be having the problem.

**Comment by netanelgonen** [comment]
I'm using the mbed-os Odin driver...

**Comment by netanelgonen** [comment]
Hi @avolinski  this is the issue we talked about

**Comment by JanneKiiskila** [comment]
We support the UBLOX_ODIN_EVK_W2 board, which used the same Odin wiFi driver, so perhaps you need to share a bit more details. Like the compilation log or something.
