### ISSUE TITLE
Pin conflict may occur by wnc14a2a-driver 

### ISSUE THREAD

**Issue by coisme** [ARMmbed/easy-connect#90]
The current revision of wnc14a2a-driver used in this project causes pin conflicts even when the wnc14a2a is not used. Here's related issue:
https://github.com/Avnet/wnc14a2a-driver/issues/6

Please apply the latest revision.

**Comment by teetak01** [comment]
@dlfryar could you check this with @jflynn129 ? Thanks.

**Comment by teetak01** [comment]
@coisme could you check if the issue is now resolved? The related change has been merged #88

**Comment by coisme** [comment]
@teetak01 Thanks. I confirmed the master branch on my environment. The issue is resolved!
